### ISSUE TITLE
kubernetes pod `exec /usr/local/bin/docker-entrypoint.sh: exec format error`

### ISSUE THREAD

**Issue by blcklamb** [doku-study/doku-study#119]
# 문제 상황

1. 2개의 image 빌드, 푸시

-`auth-api/Dockerfile`
```Dockerfile
FROM node:14-alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "node", "auth-app.js" ]
```
```bash
docker build -t blcklamb/kub-dep-example-auth .
docker push blcklamb/kub-dep-example-auth
```

- `users-api/Dockerfile`
```Dockerfile
FROM node:14-alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "node", "users-app.js" ]
```

```bash
docker build -t blcklamb/kub-dep-example-users .
docker push blcklamb/kub-dep-example-users
```

2. kubernetes deployment
- `kubernetes/auth.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-api
          image: blcklamb/kub-dep-example-auth:latest
          env:
            - name: TOKEN_KEY
              value: "shouldbeverysecure"
```

- `kubernetes/users.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: blcklamb/kub-dep-example-users:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb+srv://<username>:<password>@user-database.kaniwpt.mongodb.net/?retryWrites=true&w=majority&appName=User-database"
            - name: AUTH_API_ADDRESSS
              value: "auth-service.default:3000"
```
그 전에 EKS의 워커 노드도 잘 생성되었는지 확인했습니다.

<img width="1486" alt="image" src="https://github.com/doku-study/doku-study/assets/92101831/be657712-2ec4-4853-83d2-2c2df39d5b80">

```bash
kubectl apply -f=auth.yaml -f=users.yaml
```
<img width="858" alt="image" src="https://github.com/doku-study/doku-study/assets/92101831/20201bca-e5e7-4a14-9c9c-3c55d8ff1302">

그런데 apply를 한 뒤 pod의 상태가 `CrashLoopBackOff이고, log를 확인하니, 두 pod 모두 `exec /usr/local/bin/docker-entrypoint.sh: exec format error` 라는 로그가 뜬 것을 확인할 수 있습니다.

<img width="870" alt="image" src="https://github.com/doku-study/doku-study/assets/92101831/3e8a2f6e-e5e4-4a21-b194-7c956fb70a9c">

# 문제 원인

<img width="862" alt="image" src="https://github.com/doku-study/doku-study/assets/92101831/a9e9d5b0-257b-4ff3-877d-3de0f034736f">

# 해결 방법
